name: sync-repo-settings
on:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm link
      - run: sloth sync-repo-settings --language nodejs
        env:
          SLOTH_GITHUB_TOKEN: ${{ secrets.YOSHI_GITHUB_TOKEN }}
          DRIFT_API_KEY: ${{ secrets.DRIFT_API_KEY }}
      - run: sloth sync-repo-settings --language python
        env:
          SLOTH_GITHUB_TOKEN: ${{ secrets.YOSHI_GITHUB_TOKEN }}
          DRIFT_API_KEY: ${{ secrets.DRIFT_API_KEY }}
      - run: sloth sync-repo-settings --language java
        env:
          SLOTH_GITHUB_TOKEN: ${{ secrets.YOSHI_GITHUB_TOKEN }}
          DRIFT_API_KEY: ${{ secrets.DRIFT_API_KEY }}
